machine:
  timezone:
    America/Bogota
  java:
    version:
      oraclejdk8
  environment:
    TERM: dumb

general:
  branches:
    only:
      - master # only build/deploy from master
  artifacts:
    - "build/reports/tests" # preserve the generated HTML test reports

test:
  override:
    - ./gradlew test -is
  post:
    - mkdir -p $CIRCLE_TEST_REPORTS/junit/
    - find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;
    
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
