machine:
  timezone:
    America/Bogota
  java:
    version:
      oraclejdk8
  environment:
    TERM: dumb

general:
  branches:
    only:
      - master # only build/deploy from master
  artifacts:
    - "build/reports/tests" # preserve the generated HTML test reports
    
deployment:
  staging:
    branch: master
    heroku: 
      appname: pancomido
      
test:
  override:
    - ./gradlew test -is
  post:
    - mkdir $CIRCLE_ARTIFACTS/reports
    - exec cp -R target/site/* $CIRCLE_ARTIFACTS/reports
    - mkdir -p $CIRCLE_TEST_REPORTS/junit/
    - find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;
    
